##### test1c #####
# test1c : gestionFichier.o test1c.o
# 	gcc -o test1c test1c.o gestionFichier.o

# test1c.o : test1c.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test1c.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test2b1 #####
# test2b1 : gestionFichier.o test2b1.o
# 	gcc -o test2b1 test2b1.o gestionFichier.o

# test2b1.o : test2b1.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test2b1.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test2b2 #####
# test2b2 : gestionFichier.o test2b2.o
# 	gcc -o test2b2 test2b2.o gestionFichier.o

# test2b2.o : test2b2.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test2b2.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test2b3 #####
# test2b3 : gestionFichier.o test2b3.o
# 	gcc -o test2b3 test2b3.o gestionFichier.o

# test2b3.o : test2b3.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test2b3.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test2b4 #####
# test2b4 : gestionFichier.o test2b4.o
# 	gcc -o test2b4 test2b4.o gestionFichier.o

# test2b4.o : test2b4.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test2b4.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test2b5 #####
# test2b5 : gestionFichier.o test2b5.o
# 	gcc -o test2b5 test2b5.o gestionFichier.o

# test2b5.o : test2b5.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test2b5.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test3b1 #####
# test3b1 : gestionFichier.o test3b1.o
# 	gcc -o test3b1 test3b1.o gestionFichier.o

# test3b1.o : test3b1.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test3b1.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test3b2 #####
test3b2 : gestionFichier.o test3b2.o
	gcc -o test3b2 test3b2.o gestionFichier.o

test3b2.o : test3b2.c gestionFichier.h
	gcc -c -Wall -ansi -pedantic test3b2.c

gestionFichier.o : gestionFichier.c gestionFichier.h
	gcc -c -Wall -ansi -pedantic gestionFichier.c

##### test3b3 #####
# test3b3 : gestionFichier.o test3b3.o
# 	gcc -o test3b3 test3b3.o gestionFichier.o

# test3b3.o : test3b3.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic test3b3.c

# gestionFichier.o : gestionFichier.c gestionFichier.h
# 	gcc -c -Wall -ansi -pedantic gestionFichier.c