##### testIB1 #####
# testIB1 : gestionProcessus.o testIB1.o
# 	gcc -o testIB1 testIB1.o gestionProcessus.o

# testIB1.o : testIB1.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testIB1.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c

##### testIB2 #####
# testIB2 : gestionProcessus.o testIB2.o
# 	gcc -o testIB2 testIB2.o gestionProcessus.o

# testIB2.o : testIB2.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testIB2.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c

##### testIB3 #####
# testIB3 : gestionProcessus.o testIB3.o
# 	gcc -o testIB3 testIB3.o gestionProcessus.o

# testIB3.o : testIB3.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testIB3.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c

##### testII #####
# testII : gestionProcessus.o testII.o
# 	gcc -o testII testII.o gestionProcessus.o

# testII.o : testII.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testII.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c

##### testIII1 #####
# testIII1 : gestionProcessus.o testIII1.o
# 	gcc -o testIII1 testIII1.o gestionProcessus.o

# testIII1.o : testIII1.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testIII1.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c

##### testIII2 #####
# testIII2 : gestionProcessus.o testIII2.o
# 	gcc -o testIII2 testIII2.o gestionProcessus.o

# testIII2.o : testIII2.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testIII2.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c

##### testIII3 #####
# testIII3 : gestionProcessus.o testIII3.o
# 	gcc -o testIII3 testIII3.o gestionProcessus.o

# testIII3.o : testIII3.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic testIII3.c

# gestionProcessus.o : gestionProcessus.c gestionProcessus.h
# 	gcc -c -Wall -ansi -pedantic gestionProcessus.c